# example Iris dataset
# each data sample has 4 features, 3 labels, there are 20 samples
inputs = [
    [{ x = "47574" }, { x = "12965" }, { x = "7308" }, { x = "54267" }],
    [{ x = "23693" }, { x = "21718" }, { x = "20297" }, { x = "14813" }],
    [{ x = "53934" }, { x = "12386" }, { x = "50017" }, { x = "54209" }],
    [{ x = "64138" }, { x = "41410" }, { x = "11366" }, { x = "44367" }],
    [{ x = "33320" }, { x = "7751" }, { x = "7621" }, { x = "11809" }],
    [{ x = "19997" }, { x = "20916" }, { x = "38787" }, { x = "45122" }],
    [{ x = "7408" }, { x = "42450" }, { x = "18700" }, { x = "52594" }],
    [{ x = "48259" }, { x = "51631" }, { x = "41382" }, { x = "33162" }],
    [{ x = "20115" }, { x = "35108" }, { x = "44287" }, { x = "23900" }],
    [{ x = "58715" }, { x = "62639" }, { x = "6094" }, { x = "55398" }],
    [{ x = "58479" }, { x = "16132" }, { x = "51422" }, { x = "33365" }],
    [{ x = "27967" }, { x = "23879" }, { x = "15858" }, { x = "19779" }],
    [{ x = "55705" }, { x = "27728" }, { x = "12367" }, { x = "11747" }],
    [{ x = "30567" }, { x = "12007" }, { x = "29195" }, { x = "61210" }],
    [{ x = "28210" }, { x = "45234" }, { x = "23004" }, { x = "58564" }],
    [{ x = "8516" }, { x = "53492" }, { x = "35777" }, { x = "40811" }],
    [{ x = "13849" }, { x = "30476" }, { x = "10833" }, { x = "41847" }],
    [{ x = "24882" }, { x = "60024" }, { x = "46867" }, { x = "46204" }],
    [{ x = "63697" }, { x = "62141" }, { x = "29369" }, { x = "43506" }],
    [{ x = "18270" }, { x = "51843" }, { x = "10227" }, { x = "8672" }]
]

labels = [
    [{ x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }],
    [{ x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }],
    [{ x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }]
]

secret_key = "3"
