# example Iris dataset
# each data sample has 4 features, 3 labels, there are 10 samples
inputs = [
    [{ x = "314573" }, { x = "222822" }, { x = "104858" }, { x = "13107" }],
    [{ x = "425984" }, { x = "196608" }, { x = "340787" }, { x = "131072" }],
    [{ x = "425984" }, { x = "196608" }, { x = "360448" }, { x = "117965" }],
    [{ x = "321126" }, { x = "203162" }, { x = "98304" }, { x = "13107" }],
    [{ x = "353894" }, { x = "255590" }, { x = "85197" }, { x = "26214" }],
    [{ x = "380109" }, { x = "170394" }, { x = "262144" }, { x = "78643" }],
    [{ x = "334234" }, { x = "163840" }, { x = "196608" }, { x = "72090" }],
    [{ x = "412877" }, { x = "176947" }, { x = "321126" }, { x = "117965" }],
    [{ x = "373555" }, { x = "288358" }, { x = "98304" }, { x = "26214" }],
    [{ x = "517734" }, { x = "249037" }, { x = "419430" }, { x = "131072" }],
]

labels = [
    [{ x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }],
    [{ x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "65536" }, { x = "65536" }, { x = "0" }, { x = "65536" }],
    [{ x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }],
]

secret_key = "1"