[package]
name = "client1"
type = "bin"
authors = [""]

[dependencies]
noir_mpc_ml = { git = "https://github.com/hashcloak/noir-mpc-ml", tag = "v0.1.2" }
client_prover = { path = "../../client_prover" }