# example Iris dataset
# each data sample has 4 features, 3 labels, there are 20 samples
inputs = [
    [{ x = "51566" }, { x = "52347" }, { x = "16613" }, { x = "44878" }],
    [{ x = "20314" }, { x = "30791" }, { x = "58681" }, { x = "58470" }],
    [{ x = "47698" }, { x = "36324" }, { x = "8551" }, { x = "23147" }],
    [{ x = "30174" }, { x = "57089" }, { x = "16313" }, { x = "64756" }],
    [{ x = "19146" }, { x = "17505" }, { x = "8810" }, { x = "65025" }],
    [{ x = "55646" }, { x = "60816" }, { x = "38151" }, { x = "43850" }],
    [{ x = "17350" }, { x = "58000" }, { x = "47092" }, { x = "43030" }],
    [{ x = "6950" }, { x = "26525" }, { x = "20573" }, { x = "62001" }],
    [{ x = "44135" }, { x = "46996" }, { x = "60399" }, { x = "26780" }],
    [{ x = "11880" }, { x = "22953" }, { x = "21167" }, { x = "59697" }],
    [{ x = "44175" }, { x = "43515" }, { x = "39411" }, { x = "37596" }],
    [{ x = "64616" }, { x = "35674" }, { x = "53620" }, { x = "45618" }],
    [{ x = "15963" }, { x = "25884" }, { x = "59248" }, { x = "45805" }],
    [{ x = "27129" }, { x = "16566" }, { x = "25653" }, { x = "37914" }],
    [{ x = "9318" }, { x = "24700" }, { x = "29312" }, { x = "32745" }],
    [{ x = "48753" }, { x = "21631" }, { x = "46995" }, { x = "26137" }],
    [{ x = "51783" }, { x = "61926" }, { x = "38076" }, { x = "54788" }],
    [{ x = "13285" }, { x = "49433" }, { x = "45454" }, { x = "9933" }],
    [{ x = "30610" }, { x = "44726" }, { x = "52762" }, { x = "56710" }],
    [{ x = "41376" }, { x = "45526" }, { x = "44397" }, { x = "48530" }]
]

labels = [
    [{ x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }],
    [{ x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "65536" }, { x = "0" }],
    [{ x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" }, { x = "0" },  { x = "0" }, { x = "0" }, { x = "0" }, { x = "65536" }]
]

secret_key = "2"
