[package]
name = "masking_prover"
type = "lib"
authors = [""]

[dependencies]
noir_mpc_ml = { git = "https://github.com/hashcloak/noir-mpc-ml", tag = "v0.1.2" }
ecdh = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/ecdh" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
training_prover = { path = "../training_prover" }