[package]
name = "client2_masking"
type = "bin"
authors = [""]

[dependencies]
masking_prover = { path = "../../../provers/masking_prover" }
training_prover = { path = "../../../provers/training_prover" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }